# Copyright (c) andrysek.de
# SPDX-License-Identifier: MPL-2.0

name: CI

on:
  
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  build:
    runs-on: [self-hosted, windows]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Try to build the vmware ubuntu 22.04 machine
        run: |
          powershell.exe -Command "Remove-Item -Force -Recurse '$pwd/builds/*'"
          packer init .
          packer validate -var-file="boxes/ubuntu/22.04/vmware.pkrvars.hcl" -var-file="boxes/ubuntu/22.04/yocto.pkrvars.hcl" -var="yocto_identifier=kirkstone-4.0.16" .
          packer build -on-error=ask -only='build_vyoco.*' -var-file="boxes/ubuntu/22.04/vmware.pkrvars.hcl" -var-file="boxes/ubuntu/22.04/yocto.pkrvars.hcl" -var="yocto_identifier=kirkstone-4.0.16" .

      - name: Test created box
        run: |
          powershell.exe -Command "Remove-Item -Force -Recurse '$pwd/test/local/*'"
          cd test/local
          vagrant box add --force --provider=vmware_desktop vyoco-dev ..\..\builds\vyoco_vmware-iso_0.0.4.box
          vagrant box list
          vagrant init vyoco-dev
          vagrant up --provider=vmware_desktop
          vagrant status
          vagrant ssh -c "cd ~/workspace && ls -lsa"
          vagrant destroy -gf
          vagrant box remove vyoco-dev

          